### ISSUE TITLE
Is this project maintained anymore?

### ISSUE THREAD

**Issue by sushantdhiman** [binaryjs/binaryjs#114]
I am thinking about using binaryjs to transport live video streams. Is this project maintained anymore? Are there any other projects suggests.

**Comment by rgbkrk** [comment]
Was wondering too, noticed all the demos are offline too. :cry:

**Comment by sushantdhiman** [comment]
I end up using [Kurento Media Server](http://www.kurento.org) and their JS APIs. I cant risk using BinaryJS  :disappointed: for now.
