### ISSUE TITLE
 Unhandled 'error' event

### ISSUE THREAD

**Issue by ToniNgethe** [binaryjs/binaryjs#131]
I keep getting this error  whenever i use binaryjs together with sockets.io  in nodejs using the express server

`events.js:174`
      `throw er; // Unhandled 'error' event`
      `^`

`Error: read ECONNRESET`
    `at TCP.onStreamRead (internal/stream_base_commons.js:111:27)`
`Emitted 'error' event at:`
    `at emitErrorNT (internal/streams/destroy.js:91:8)`
    `at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)`
   ` at process._tickCallback (internal/process/next_tick.js:63:19) `
`

My connection to binaryjs is 

` const bs = new BinaryServer({ server: server, path: '/binary' });`

**Comment by Cabezas2020** [comment]
Hello, were you able to fix this issue?

**Comment by tinawng** [comment]
Fix posted here:
[https://github.com/binaryjs/streamws/pull/2](https://github.com/binaryjs/streamws/pull/2)
