### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by dominictarr** [binaryjs/binaryjs#4]
I just get "not implemented" on the hello world example

I'm in chrome Version 20.0.1132.21 beta

is that too old?

also, it would probably be better to host the binary.js bundle from the example server, so it's easier to update when doing development.

p.s.

Great that you have used streams! 
I'm very happy you've done this the right way!

**Comment by hsnbilgen** [comment]
Actually hellow world example did not worked for me too do i need to add libraries on it?
